/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_putao_ptx_image_service_ImageProcess */

#ifndef _Included_com_putao_ptx_image_service_ImageProcess
#define _Included_com_putao_ptx_image_service_ImageProcess
#ifdef __cplusplus
extern "C" {
#endif
    
JNIEXPORT jboolean JNICALL Java_com_putao_ptx_image_service_ImageProcess_stitch
  (JNIEnv *, jclass, jobjectArray, jstring);

/*
 * Class:     com_putao_ptx_camera_ImageProcess
 * Method:    cropImage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_putao_ptx_image_service_ImageProcess_cropImage
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
